FROM golang:1.25-bookworm AS builder

RUN apt-get update && \
    apt-get install -y nodejs npm && \
    npm install -g yarn@1.22.22

WORKDIR /app

COPY . .

ENV GO111MODULE=on

RUN make download-tools install generate build-bin-local

FROM scratch

WORKDIR /opt/traggo

COPY --from=builder /app/build/traggo-server /opt/traggo/traggo

EXPOSE 3030

ENTRYPOINT ["./traggo"]
