# syntax=docker/dockerfile:1.7

FROM node:20-bookworm AS ui-builder

WORKDIR /app
COPY schema.graphql ./
COPY ui/package.json ui/yarn.lock ./ui/
RUN corepack enable \
 && corepack prepare yarn@1.22.22 --activate \
 && cd ui \
 && yarn config set registry https://registry.npmjs.org \
 && yarn config set network-timeout 600000 \
 && sed -i 's#https://registry.yarnpkg.com#https://registry.npmjs.org#g' yarn.lock \
 && yarn install --frozen-lockfile

COPY ui ./ui
RUN cd ui \
    && yarn generate \
    && NODE_OPTIONS=--openssl-legacy-provider yarn build

FROM golang:1.25-bookworm AS server-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY --from=ui-builder /app/ui/build ./ui/build

RUN go run github.com/99designs/gqlgen@v0.17.85 \
    && CGO_ENABLED=1 go build \
        -a \
        -tags "netgo osusergo sqlite_omit_load_extension" \
        -ldflags '-s -w -linkmode external -extldflags "-static" -X main.BuildMode=prod -X main.BuildVersion=portainer' \
        -o /traggo

FROM scratch

WORKDIR /opt/traggo
COPY --from=server-builder --chmod=0755 /traggo /opt/traggo/traggo

EXPOSE 3030
STOPSIGNAL SIGTERM
ENTRYPOINT ["/opt/traggo/traggo"]
